title: jsSocials
email: tabalinas@gmail.com
description: Social Network Sharing jQuery Plugin
baseurl: ""
url: "http://js-socials.com"
twitter_username: artem_tabalin
github_username:  tabalinas
sass:
  sass_dir: _scss
collections:
  - demos
markdown: redcarpet
highlighter: rouge
