title: jsSocials
email: tabalinas@gmail.com
description: Simple Social Network Sharing Plugin
baseurl: ""
url: "http://js-socials.com"
twitter: artem_tabalin
github:  tabalinas
version: 1.3.1
sass:
  sass_dir: _scss
collections:
  - demos
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
